apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: my-app
spec:
  type: NodePort
  selector:
    app: website
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000 

