apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-demo
  namespace: argocd
spec:
  generators:
  # This is a list generator, reference here https://argocd-applicationset.readthedocs.io/en/stable/Generators-List/
  - list:
      elements:
      - name: storage
        path: argocd/storage
        image_list: storage=${storage_repository}
      - name: convert
        path: argocd/convert
        image_list: convert=${convert_repository}
      - name: website
        path: argocd/website
        image_list: website=${website_repository}
  template:
    metadata:
      name: '{{name}}' # /!\ important
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        # https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#available-annotations
        argocd-image-updater.argoproj.io/image-list: '{{image_list}}'
        argocd-image-updater.argoproj.io/{{name}}.pull-secret: secret:argocd/aws-ecr-creds#creds
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    spec:
      project: default

      source:
        repoURL: ${github_repo_infra}
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        syncOptions: 
          - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true